pipeline {
    agent { label "app-1" }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }

        stage('New Stage') {
            steps {
                echo 'Hello Stage 2'
                sh "date"
                sh "hostname"
            }
        }
    }
}
