pipeline {
    agent { label "testing-agent" }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                echo 'Multi branch demo'
                echo 'Running from a new branch'
            }
        }

        stage('New Stage') {
            steps {
                echo 'Hello Stage 2'
                sh "date"
                sh "hostname"
            }
        }
    }
}
