services:
  jenkins:
    image: jenkins/jenkins:lts
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBKEY}
    ports:
      - "2200:22"
volumes:
  jenkins_home:
